import { router } from 'expo-router';
import { useEffect, useMemo, useRef, useState } from 'react';
import { AccessibilityInfo, ActivityIndicator, Dimensions, FlatList, ImageBackground, Pressable, RefreshControl, ScrollView, StyleSheet, Text, View } from 'react-native';
import { listAdventures } from '../../src/adventures/api';
import type { AdventureSummary } from '../../src/adventures/types';
import { getGroups } from '../../src/community/api';
import { supabase } from '../../src/lib/supabase';
import { getJourney, getPassportStamps, getMemberBadges } from '../../src/passport/api';
import { getAdventureQueue } from '../../src/readiness/api';
import type { AdventureQueueItem } from '../../src/readiness/types';
import { getWeather, type WeatherForecast } from '../../src/weather/api';

const W=Dimensions.get('window').width-36;
function greeting(h:number){return h<12?'Good morning':h<18?'Good afternoon':'Good evening'}
function rankFor(n:number){if(n>=20)return'Legacy Adventurer';if(n>=10)return'Summiteer';if(n>=5)return'Wayfinder';if(n>=3)return'Trailblazer';if(n>=1)return'Pathfinder';return'Explorer'}
function date(v:string){return new Date(v).toLocaleDateString(undefined,{month:'short',day:'numeric'})}

export default function TrailheadScreen(){
 const [queue,setQueue]=useState<AdventureQueueItem[]>([]),[adventures,setAdventures]=useState<AdventureSummary[]>([]),[first,setFirst]=useState('Adventurer'),[location,setLocation]=useState(''),[groups,setGroups]=useState(0),[journey,setJourney]=useState<any[]>([]),[stamps,setStamps]=useState(0),[badges,setBadges]=useState(0),[weather,setWeather]=useState<WeatherForecast|null>(null),[loading,setLoading]=useState(true),[refreshing,setRefreshing]=useState(false),[error,setError]=useState<string|null>(null),[active,setActive]=useState(1),[paused,setPaused]=useState(false),[reduceMotion,setReduceMotion]=useState(false);
 const listRef=useRef<FlatList<AdventureSummary>>(null); const resumeTimer=useRef<ReturnType<typeof setTimeout>|null>(null);
 const featured=useMemo(()=>adventures.filter(a=>a.status!=='cancelled').slice(0,5),[adventures]);
 const loop=useMemo(()=>featured.length>1?[featured[featured.length-1],...featured,featured[0]]:featured,[featured]);
 async function load(refresh=false){refresh?setRefreshing(true):setLoading(true);try{const {data:s}=await supabase.auth.getSession();const uid=s.session?.user.id;const [q,g,j,ps,pb,a,p]=await Promise.all([getAdventureQueue(),getGroups(),getJourney(),getPassportStamps(),getMemberBadges(),listAdventures(),uid?supabase.from('profiles').select('first_name,display_name,home_city,home_state').eq('id',uid).single():Promise.resolve({data:null,error:null})]);setQueue(q);setGroups(g.filter(x=>x.is_member).length);setJourney(j);setStamps(ps.length);setBadges(pb.length);setAdventures(a);const x=p.data as any;setFirst(x?.first_name||x?.display_name?.split(' ')[0]||'Adventurer');const loc=[x?.home_city,x?.home_state].filter(Boolean).join(', ');setLocation(loc);if(x?.home_city&&x?.home_state){getWeather(x.home_city,x.home_state).then(setWeather).catch(()=>setWeather(null))}setError(null)}catch(e){setError(e instanceof Error?e.message:'Unable to load Trailhead.')}finally{setLoading(false);setRefreshing(false)}}
 useEffect(()=>{void load();AccessibilityInfo.isReduceMotionEnabled().then(setReduceMotion)},[]);
 useEffect(()=>{if(reduceMotion||paused||loop.length<2)return;const t=setInterval(()=>{setActive(i=>{const n=i+1;listRef.current?.scrollToIndex({index:n,animated:true});return n})},5000);return()=>clearInterval(t)},[reduceMotion,paused,loop.length]);
 function pause(){setPaused(true);if(resumeTimer.current)clearTimeout(resumeTimer.current);resumeTimer.current=setTimeout(()=>setPaused(false),4500)}
 function settle(i:number){if(featured.length<2)return;let n=i;if(i===0){n=featured.length;listRef.current?.scrollToIndex({index:n,animated:false})}else if(i===featured.length+1){n=1;listRef.current?.scrollToIndex({index:n,animated:false})}setActive(n)}
 const states=new Set(journey.map((x:any)=>x.state).filter(Boolean)); const currentRank=rankFor(journey.length);
 return <ScrollView style={s.screen} contentContainerStyle={s.content} refreshControl={<RefreshControl refreshing={refreshing} onRefresh={()=>void load(true)} tintColor="#D7B45A"/>}>
  <View style={s.top}><View style={s.mark}><Text style={s.markText}>MA</Text></View><View style={s.actions}><Pressable onPress={()=>router.push('/notifications')}><Text style={s.topLink}>Alerts</Text></Pressable><Pressable onPress={()=>router.push('/member/profile')}><Text style={s.topLink}>Profile</Text></Pressable></View></View>
  <Text style={s.greet}>{greeting(new Date().getHours())}, {first}</Text><Text style={s.title}>What’s next on your trail?</Text>
  {loading?<ActivityIndicator color="#D7B45A" style={{margin:18}}/>:null}{error?<Text style={s.error}>{error}</Text>:null}
  {featured.length?<View style={s.section}><View style={s.sectionRow}><Text style={s.sectionTitle}>Featured Adventures</Text><Text style={s.count}>{featured.length>1?`${Math.max(1,Math.min(featured.length,active))} of ${featured.length}`:'1 of 1'}</Text></View><FlatList ref={listRef} horizontal data={loop} keyExtractor={(x,i)=>`${x.id}-${i}`} initialScrollIndex={featured.length>1?1:0} getItemLayout={(_,i)=>({length:W,offset:W*i,index:i})} pagingEnabled showsHorizontalScrollIndicator={false} onTouchStart={pause} onScrollBeginDrag={pause} onMomentumScrollEnd={e=>settle(Math.round(e.nativeEvent.contentOffset.x/W))} renderItem={({item})=><Pressable style={{width:W}} onPress={()=>router.push({pathname:'/adventures/[id]',params:{id:item.id}})}><ImageBackground source={item.hero_image_url?{uri:item.hero_image_url}:undefined} style={s.hero} imageStyle={s.heroRadius}><View style={s.shade}/><View style={s.heroBody}><Text style={s.eyebrow}>{item.is_featured?'FEATURED ADVENTURE':'OFFICIAL MA ADVENTURE'}</Text><Text style={s.heroTitle}>{item.title}</Text><Text style={s.heroMeta}>{date(item.starts_at)} · {item.city}, {item.state}</Text><Text style={s.heroAction}>View Adventure →</Text></View></ImageBackground></Pressable>}/></View>:null}
  {weather?<Pressable style={s.weather} onPress={()=>router.push('/member/weather' as never)}><View><Text style={s.eyebrow}>WEATHER · SAVED LOCATION</Text><Text style={s.weatherTitle}>{weather.location.name}, {weather.location.region} · {Math.round(weather.current.temp_f)}°</Text><Text style={s.muted}>{weather.current.condition.text} · Feels {Math.round(weather.current.feelslike_f)}°</Text></View><Text style={s.weatherGlyph}>☁︎</Text></Pressable>:<Pressable style={s.weather} onPress={()=>router.push('/member/weather' as never)}><View><Text style={s.eyebrow}>WEATHER</Text><Text style={s.weatherTitle}>{location||'Set your location'}</Text><Text style={s.muted}>Open Weather & Location</Text></View><Text style={s.weatherGlyph}>☁︎</Text></Pressable>}
  <View style={s.duo}><Pressable style={s.half} onPress={()=>router.push('/(tabs)/community')}><Text style={s.eyebrow}>COMMUNITY · WHAT’S HAPPENING</Text><Text style={s.big}>{groups}</Text><Text style={s.cardTitle}>Your Groups</Text><Text style={s.muted}>Adventure, local and interest communities.</Text><Text style={s.link}>View Groups →</Text></Pressable><Pressable style={s.half} onPress={()=>router.push('/(tabs)/passport')}><Text style={s.eyebrow}>PASSPORT</Text><Text style={s.cardTitle}>{currentRank}</Text><Text style={s.big}>{stamps}</Text><Text style={s.muted}>{stamps} stamps · {badges} badges</Text><Text style={s.link}>View Passport →</Text></Pressable></View>
  <Pressable style={s.journey} onPress={()=>router.push('/(tabs)/passport')}><Text style={s.eyebrow}>MY JOURNEY</Text><View style={s.journeyStats}><View><Text style={s.stat}>{journey.length}</Text><Text style={s.statLabel}>Adventures</Text></View><View><Text style={s.stat}>{states.size}</Text><Text style={s.statLabel}>States</Text></View><View><Text style={s.stat}>{groups}</Text><Text style={s.statLabel}>Communities</Text></View></View><Text style={s.link}>Open Journey in Passport →</Text></Pressable>
  <View style={s.section}><View style={s.sectionRow}><Text style={s.sectionTitle}>Current Reservations</Text><Pressable onPress={()=>router.push('/member/trips')}><Text style={s.link}>Manage</Text></Pressable></View>{queue.length?<ScrollView horizontal showsHorizontalScrollIndicator={false} contentContainerStyle={{gap:10}}>{queue.slice(0,4).map(q=><Pressable key={q.order_id} style={s.reservation} onPress={()=>router.push('/member/trips')}><Text style={s.eyebrow}>{q.order_status==='held'||q.order_status==='payment_pending'?'RESERVATION HELD':'CONFIRMED'}</Text><Text style={s.cardTitle}>{q.title}</Text><Text style={s.muted}>{date(q.starts_at)} · {q.city}, {q.state}</Text><Text style={s.link}>{q.order_status==='held'?'Continue payment →':'View Reservation →'}</Text></Pressable>)}</ScrollView>:<View style={s.empty}><Text style={s.cardTitle}>No active reservations</Text><Text style={s.muted}>When you book an Adventure, the essentials will live here.</Text></View>}</View>
  <View style={s.section}><View style={s.sectionRow}><Text style={s.sectionTitle}>Upcoming Adventures</Text><Pressable onPress={()=>router.push('/(tabs)/explore')}><Text style={s.link}>Explore</Text></Pressable></View><ScrollView horizontal showsHorizontalScrollIndicator={false} contentContainerStyle={{gap:10}}>{adventures.slice(0,5).map(a=><Pressable key={a.id} style={s.upcoming} onPress={()=>router.push({pathname:'/adventures/[id]',params:{id:a.id}})}><ImageBackground source={a.hero_image_url?{uri:a.hero_image_url}:undefined} style={s.thumb} imageStyle={{borderRadius:14}}/><Text style={s.upTitle} numberOfLines={2}>{a.title}</Text><Text style={s.muted}>{date(a.starts_at)} · {a.city}</Text></Pressable>)}</ScrollView></View>
 </ScrollView>
}
const s=StyleSheet.create({screen:{flex:1,backgroundColor:'#0F1713'},content:{paddingHorizontal:18,paddingTop:52,paddingBottom:42,gap:15},top:{flexDirection:'row',justifyContent:'space-between',alignItems:'center'},mark:{width:52,height:42,borderWidth:1,borderColor:'#D7B45A',borderRadius:14,alignItems:'center',justifyContent:'center'},markText:{color:'#D7B45A',fontWeight:'900',letterSpacing:1.7,fontSize:18},actions:{flexDirection:'row',gap:18},topLink:{color:'#E3D8BB',fontWeight:'800'},greet:{color:'#D7B45A',fontWeight:'800',marginTop:8},title:{color:'#FFF8E8',fontSize:35,lineHeight:39,fontWeight:'900'},error:{color:'#FFB4A9'},section:{gap:10},sectionRow:{flexDirection:'row',justifyContent:'space-between',alignItems:'center'},sectionTitle:{color:'#FFF8E8',fontSize:21,fontWeight:'900'},count:{color:'#7F8C84',fontSize:12},hero:{height:300,justifyContent:'flex-end',backgroundColor:'#26372D',borderRadius:24,overflow:'hidden'},heroRadius:{borderRadius:24},shade:{...StyleSheet.absoluteFillObject,backgroundColor:'rgba(7,12,9,.48)'},heroBody:{padding:20,gap:6},eyebrow:{color:'#D7B45A',fontSize:10,fontWeight:'900',letterSpacing:1},heroTitle:{color:'#FFF8E8',fontSize:28,lineHeight:31,fontWeight:'900'},heroMeta:{color:'#E0E5E1'},heroAction:{color:'#F0D083',fontWeight:'900',marginTop:4},weather:{backgroundColor:'#1A2821',borderRadius:18,borderWidth:1,borderColor:'#32453A',padding:16,flexDirection:'row',justifyContent:'space-between',alignItems:'center'},weatherTitle:{color:'#FFF8E8',fontSize:17,fontWeight:'900',marginTop:5},weatherGlyph:{color:'#F0D083',fontSize:32},muted:{color:'#96A39B',lineHeight:19,marginTop:3},duo:{flexDirection:'row',gap:10},half:{flex:1,minHeight:180,backgroundColor:'#17211C',borderRadius:18,borderWidth:1,borderColor:'#28362E',padding:15},big:{color:'#FFF8E8',fontSize:30,fontWeight:'900',marginTop:10},cardTitle:{color:'#FFF8E8',fontSize:18,fontWeight:'900',marginTop:5},link:{color:'#D7B45A',fontWeight:'900',marginTop:8},journey:{backgroundColor:'#17211C',borderRadius:20,borderWidth:1,borderColor:'#3A493F',padding:17},journeyStats:{flexDirection:'row',justifyContent:'space-between',marginTop:13},stat:{color:'#FFF8E8',fontSize:26,fontWeight:'900'},statLabel:{color:'#8F9A93',fontSize:11,marginTop:2},reservation:{width:270,backgroundColor:'#1A2821',borderRadius:18,borderWidth:1,borderColor:'#33483B',padding:16},empty:{backgroundColor:'#17211C',borderRadius:18,padding:16},upcoming:{width:165,backgroundColor:'#17211C',borderRadius:16,padding:10},thumb:{width:'100%',height:105,backgroundColor:'#26372D'},upTitle:{color:'#FFF8E8',fontWeight:'900',fontSize:15,lineHeight:19,marginTop:9}});
