import { router } from 'expo-router';
import * as Location from 'expo-location';
import { useEffect, useState } from 'react';
import { ActivityIndicator, Pressable, ScrollView, StyleSheet, Text, View } from 'react-native';
import { SafeAreaView } from 'react-native-safe-area-context';
import { getMemberBasecamp } from '../../src/member/api';
import { getWeather, getWeatherByCoordinates, type WeatherForecast } from '../../src/weather/api';

export default function WeatherScreen(){const [data,setData]=useState<WeatherForecast|null>(null),[saved,setSaved]=useState<{city:string;state:string}|null>(null),[loading,setLoading]=useState(true),[mode,setMode]=useState<'saved'|'current'>('saved'),[error,setError]=useState('');
 async function loadSaved(){setLoading(true);setError('');try{const b=await getMemberBasecamp();const city=b.profile?.home_city,state=b.profile?.home_state;if(!city||!state)throw new Error('Set a city and state in Edit Profile first.');setSaved({city,state});setData(await getWeather(city,state));setMode('saved')}catch(e){setError(e instanceof Error?e.message:'Unable to load weather.')}finally{setLoading(false)}}
 async function loadCurrent(){setLoading(true);setError('');try{const p=await Location.requestForegroundPermissionsAsync();if(p.status!=='granted')throw new Error('Location permission is needed to use Current Location.');const loc=await Location.getCurrentPositionAsync({accuracy:Location.Accuracy.Balanced});setData(await getWeatherByCoordinates(loc.coords.latitude,loc.coords.longitude));setMode('current')}catch(e){setError(e instanceof Error?e.message:'Unable to use current location.')}finally{setLoading(false)}}
 useEffect(()=>{void loadSaved()},[]);const c=data?.current,l=data?.location,days=data?.forecast?.forecastday??[];
 return <SafeAreaView style={s.safe}><ScrollView contentContainerStyle={s.content}><Pressable onPress={()=>router.back()}><Text style={s.back}>‹ Back</Text></Pressable><Text style={s.eyebrow}>WEATHER & LOCATION</Text><Text style={s.title}>Trail weather</Text><Text style={s.intro}>Profile location stays saved to your account. Current Location is temporary and does not overwrite it.</Text><View style={s.toggle}><Pressable style={[s.toggleBtn,mode==='saved'&&s.active]} onPress={()=>void loadSaved()}><Text style={[s.toggleText,mode==='saved'&&s.activeText]}>Use Saved Location</Text></Pressable><Pressable style={[s.toggleBtn,mode==='current'&&s.active]} onPress={()=>void loadCurrent()}><Text style={[s.toggleText,mode==='current'&&s.activeText]}>Use Current Location</Text></Pressable></View>{loading?<ActivityIndicator color="#D7B45A" style={{margin:24}}/>:null}{error?<View style={s.card}><Text style={s.error}>{error}</Text>{!saved?<Pressable onPress={()=>router.push('/member/profile')}><Text style={s.link}>Edit Profile →</Text></Pressable>:null}</View>:null}{data&&!loading?<><View style={s.hero}><Text style={s.location}>{l?.name}, {l?.region}</Text><Text style={s.temp}>{Math.round(c?.temp_f??0)}°</Text><Text style={s.condition}>{c?.condition?.text}</Text><Text style={s.meta}>Feels {Math.round(c?.feelslike_f??0)}° · Humidity {c?.humidity}% · Wind {Math.round(c?.wind_mph??0)} mph</Text></View><Text style={s.section}>3-day outlook</Text>{days.map(d=><View key={d.date} style={s.day}><View><Text style={s.dayTitle}>{new Date(`${d.date}T12:00:00`).toLocaleDateString(undefined,{weekday:'long',month:'short',day:'numeric'})}</Text><Text style={s.condition}>{d.day.condition.text}</Text></View><View style={{alignItems:'flex-end'}}><Text style={s.range}>{Math.round(d.day.maxtemp_f)}° / {Math.round(d.day.mintemp_f)}°</Text><Text style={s.rain}>{d.day.daily_chance_of_rain}% rain</Text></View></View>)}</>:null}</ScrollView></SafeAreaView>}
const s=StyleSheet.create({safe:{flex:1,backgroundColor:'#0F1713'},content:{padding:20,paddingBottom:60,gap:12},back:{color:'#D7B45A',fontWeight:'900'},eyebrow:{color:'#D7B45A',fontSize:11,fontWeight:'900',letterSpacing:1.1,marginTop:8},title:{color:'#FFF8E8',fontSize:34,fontWeight:'900'},intro:{color:'#9DA8A1',lineHeight:21},toggle:{flexDirection:'row',backgroundColor:'#151F1A',borderRadius:14,padding:4,gap:4},toggleBtn:{flex:1,paddingVertical:10,paddingHorizontal:7,borderRadius:11,alignItems:'center'},active:{backgroundColor:'#D7B45A'},toggleText:{color:'#AAB4AE',fontWeight:'800',fontSize:12,textAlign:'center'},activeText:{color:'#17211C'},card:{backgroundColor:'#17211C',borderRadius:16,padding:16},error:{color:'#FFB4A9',lineHeight:20},link:{color:'#D7B45A',fontWeight:'900',marginTop:8},hero:{backgroundColor:'#1B2A22',borderRadius:22,borderWidth:1,borderColor:'#33483B',padding:22},location:{color:'#F0D083',fontWeight:'900'},temp:{color:'#FFF8E8',fontSize:60,fontWeight:'900',marginTop:7},condition:{color:'#D6DFD9',fontSize:16,marginTop:2},meta:{color:'#94A198',marginTop:10},section:{color:'#FFF8E8',fontSize:21,fontWeight:'900',marginTop:7},day:{backgroundColor:'#17211C',borderRadius:16,borderWidth:1,borderColor:'#28362E',padding:15,flexDirection:'row',justifyContent:'space-between',alignItems:'center',gap:12},dayTitle:{color:'#FFF8E8',fontWeight:'900'},range:{color:'#FFF8E8',fontSize:18,fontWeight:'900'},rain:{color:'#D7B45A',fontSize:12,marginTop:3}});
