import { router } from 'expo-router';
import { useState } from 'react';
import { ActivityIndicator, Pressable, SafeAreaView, ScrollView, StyleSheet, Text, TextInput, View } from 'react-native';
import { createHostOrganization } from '../../src/hosting/hostProfiles';

const C={bg:'#0A0F0C',panel:'#131B16',line:'#2D3A32',cream:'#FFF8E8',muted:'#95A29A',gold:'#D7B45A'};

export default function NewOrganizationHostProfileScreen(){
 const [name,setName]=useState(''); const [description,setDescription]=useState(''); const [city,setCity]=useState(''); const [state,setState]=useState(''); const [saving,setSaving]=useState(false); const [error,setError]=useState('');
 async function create(){setSaving(true);setError('');try{const org=await createHostOrganization({name,description,city,state});router.replace(`/host/organization/${org.id}` as never);}catch(caught){setError(caught instanceof Error?caught.message:'Unable to create host profile.');}finally{setSaving(false)}}
 return <SafeAreaView style={styles.safe}><ScrollView contentContainerStyle={styles.content} keyboardShouldPersistTaps="handled">
  <Pressable onPress={()=>router.back()}><Text style={styles.back}>‹ Host profiles</Text></Pressable>
  <Text style={styles.eyebrow}>NEW HOST PROFILE</Text><Text style={styles.title}>Create a hosting identity</Text><Text style={styles.copy}>Every host profile is an organization. If you host by yourself, use your own name.</Text>
  {error?<View style={styles.errorCard}><Text style={styles.error}>{error}</Text></View>:null}
  <View style={styles.card}><Field label="Organization or host name" value={name} onChangeText={setName} placeholder="Melanated Adventurers"/><Field label="Short description" value={description} onChangeText={setDescription} placeholder="Outdoor community and event host" multiline/><View style={styles.row}><View style={styles.flex}><Field label="City" value={city} onChangeText={setCity} placeholder="Jacksonville"/></View><View style={styles.state}><Field label="State" value={state} onChangeText={setState} placeholder="FL"/></View></View><Pressable disabled={saving||!name.trim()} style={[styles.primary,(saving||!name.trim())&&styles.disabled]} onPress={()=>void create()}>{saving?<ActivityIndicator color="#162019"/>:<Text style={styles.primaryText}>Create host profile</Text>}</Pressable></View>
 </ScrollView></SafeAreaView>
}
function Field({label,multiline=false,...props}:any){return <View style={styles.field}><Text style={styles.label}>{label}</Text><TextInput {...props} multiline={multiline} textAlignVertical={multiline?'top':'center'} placeholderTextColor="#657269" style={[styles.input,multiline&&styles.multiline]}/></View>}
const styles=StyleSheet.create({safe:{flex:1,backgroundColor:C.bg},content:{padding:20,paddingBottom:100},back:{color:C.gold,fontWeight:'900',marginBottom:14},eyebrow:{color:C.gold,fontSize:10,fontWeight:'900',letterSpacing:1.1},title:{color:C.cream,fontSize:30,fontWeight:'900',marginTop:3},copy:{color:C.muted,fontSize:12,lineHeight:18,marginTop:6,maxWidth:620},card:{marginTop:18,backgroundColor:C.panel,borderRadius:18,borderWidth:1,borderColor:C.line,padding:16},field:{marginTop:12},label:{color:C.cream,fontSize:10,fontWeight:'800',marginBottom:6},input:{minHeight:46,borderRadius:12,borderWidth:1,borderColor:C.line,backgroundColor:'#101611',color:C.cream,paddingHorizontal:12,fontSize:12},multiline:{minHeight:96,paddingTop:12},row:{flexDirection:'row',gap:10},flex:{flex:1},state:{width:110},primary:{minHeight:48,borderRadius:12,backgroundColor:C.gold,alignItems:'center',justifyContent:'center',marginTop:18},primaryText:{color:'#162019',fontWeight:'900',fontSize:12},disabled:{opacity:.45},errorCard:{marginTop:14,backgroundColor:'#251614',borderWidth:1,borderColor:'#6A3E38',borderRadius:13,padding:12},error:{color:'#F0A199'}});
