alter table public.host_vendor_profiles
  add column if not exists marketplace_visible boolean not null default false,
  add column if not exists marketplace_category text,
  add column if not exists marketplace_subcategory text,
  add column if not exists vendor_kind text not null default 'service' check (vendor_kind in ('service','product','venue')),
  add column if not exists availability_status text not null default 'contact' check (availability_status in ('available','limited','booking_ahead','contact','unavailable')),
  add column if not exists verification_status text not null default 'profile_complete' check (verification_status in ('new','profile_complete','go_melanated_verified','documents_verified')),
  add column if not exists starting_price_text text,
  add column if not exists travel_radius_miles integer check (travel_radius_miles is null or travel_radius_miles >= 0),
  add column if not exists event_types text[] not null default '{}'::text[],
  add column if not exists response_time_text text,
  add column if not exists featured boolean not null default false;

create index if not exists host_vendor_profiles_marketplace_idx
  on public.host_vendor_profiles(marketplace_visible, marketplace_category, marketplace_subcategory);

create table if not exists public.host_saved_vendors (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references public.profiles(id) on delete cascade,
  vendor_profile_id uuid not null references public.host_vendor_profiles(id) on delete cascade,
  created_at timestamptz not null default now(),
  unique (user_id, vendor_profile_id)
);

alter table public.host_saved_vendors enable row level security;
grant select, insert, delete on table public.host_saved_vendors to authenticated;

create policy "Members can read own saved vendors" on public.host_saved_vendors
  for select to authenticated using (user_id = (select auth.uid()));
create policy "Members can save vendors" on public.host_saved_vendors
  for insert to authenticated with check (user_id = (select auth.uid()));
create policy "Members can remove own saved vendors" on public.host_saved_vendors
  for delete to authenticated using (user_id = (select auth.uid()));

insert into public.host_vendor_profiles (
  business_name, category, description, contact_name, email, phone, website,
  service_area, documents, internal_notes, is_demo, demo_key, sample_pricing,
  typical_setup, demo_event_count, rating, marketplace_visible, marketplace_category,
  marketplace_subcategory, vendor_kind, availability_status, verification_status,
  starting_price_text, travel_radius_miles, event_types, response_time_text, featured
) values
('Southern Smoke Kitchen','Catering','Southern comfort catering for outdoor events, reunions and festivals.','Avery Brooks','hello@southernsmoke.example.com','(904) 555-0101','https://southernsmoke.example.com','Jacksonville and Northeast Florida','{"w9":"on_file","insurance":"on_file","food_permit":"on_file"}','DEMO VENDOR. Marketplace test record.',true,'market-demo-catering-southern-smoke','{"per_person_from_cents":1800}','{"booth_size":"10x20","power_required":true,"water_required":true}',6,4.8,true,'Food & Beverage','Catering','service','available','documents_verified','From $18/person',75,array['Camping','Festivals','Family Events'],'Usually replies within 2 hours',true),
('Rolling Jerk Co.','Food Truck','Caribbean-inspired mobile food vendor for community events and festivals.','Jordan Miles','events@rollingjerk.example.com','(904) 555-0102','https://rollingjerk.example.com','Jacksonville, St. Augustine and surrounding areas','{"w9":"on_file","insurance":"on_file","food_permit":"on_file"}','DEMO VENDOR. Marketplace test record.',true,'market-demo-foodtruck-rolling-jerk','{"minimum_event_cents":90000}','{"booth_size":"truck","power_required":false,"water_required":false}',5,4.7,true,'Food & Beverage','Food Trucks','service','booking_ahead','go_melanated_verified','$900 minimum',60,array['Festivals','Community Events','Markets'],'Usually replies same day',true),
('Sweet Ember Bakery','Desserts','Cupcakes, cookies, mini pies and event dessert tables.','Nia Carter','orders@sweetember.example.com','(904) 555-0103','https://sweetember.example.com','Jacksonville and Orange Park','{"w9":"on_file","insurance":"on_file"}','DEMO VENDOR. Marketplace test record.',true,'market-demo-desserts-sweet-ember','{"dessert_table_from_cents":65000}','{"booth_size":"10x10","power_required":true,"water_required":false}',4,4.9,true,'Food & Beverage','Desserts','service','available','documents_verified','From $650/event',40,array['Weddings','Camping','Family Events'],'Usually replies within 4 hours',false),
('Brew Trail Coffee Cart','Coffee','Mobile coffee and cold brew cart for morning events and vendor markets.','Maya Fields','hello@brewtrail.example.com','(904) 555-0113','https://brewtrail.example.com','Northeast Florida','{"w9":"on_file","insurance":"on_file"}','DEMO VENDOR. Marketplace test record.',true,'market-demo-coffee-brew-trail','{"service_from_cents":55000}','{"booth_size":"8x8","power_required":true,"water_required":true}',3,4.7,true,'Food & Beverage','Coffee','service','limited','profile_complete','From $550/event',80,array['Markets','Retreats','Camping'],'Usually replies same day',false),
('Rooted Gold Jewelry','Jewelry','Handmade jewelry and statement pieces for pop-up markets.','Amina Wells','market@rootedgold.example.com','(904) 555-0114','https://rootedgold.example.com','Jacksonville and regional travel','{"insurance":"on_file"}','DEMO VENDOR. Marketplace test record.',true,'market-demo-jewelry-rooted-gold','{"typical_item_from_cents":2800}','{"booth_size":"10x10","power_required":false,"water_required":false}',8,4.9,true,'Retail & Sales','Jewelry','product','available','go_melanated_verified','Items from $28',120,array['Markets','Festivals','Community Events'],'Usually replies within 3 hours',true),
('Trail Threads Co.','Apparel','Outdoor lifestyle apparel, hats and event-ready pop-up retail.','Darius King','sales@trailthreads.example.com','(904) 555-0115','https://trailthreads.example.com','Florida','{"insurance":"on_file"}','DEMO VENDOR. Marketplace test record.',true,'market-demo-apparel-trail-threads','{"typical_item_from_cents":2400}','{"booth_size":"10x10","power_required":false,"water_required":false}',7,4.6,true,'Retail & Sales','Apparel','product','booking_ahead','profile_complete','Items from $24',250,array['Camping','Festivals','Markets'],'Usually replies same day',false),
('Black Pine Art House','Art','Prints, original art and live event art activations.','Simone Reed','studio@blackpineart.example.com','(904) 555-0116','https://blackpineart.example.com','North Florida','{}','DEMO VENDOR. Marketplace test record.',true,'market-demo-art-black-pine','{"prints_from_cents":2000}','{"booth_size":"10x10","power_required":false,"water_required":false}',2,4.8,true,'Retail & Sales','Art','product','available','new','Prints from $20',100,array['Markets','Community Events','Festivals'],'Usually replies within 1 day',false),
('Glow Root Candle Co.','Candles','Small-batch candles and scent bars for pop-up markets.','Keisha Hall','hello@glowroot.example.com','(904) 555-0117','https://glowroot.example.com','Jacksonville metro','{"insurance":"pending"}','DEMO VENDOR. Marketplace test record.',true,'market-demo-gifts-glow-root','{"candles_from_cents":1800}','{"booth_size":"10x10","power_required":false,"water_required":false}',1,4.5,true,'Retail & Sales','Gifts','product','available','profile_complete','Items from $18',45,array['Markets','Holiday Events','Community Events'],'Usually replies same day',false),
('Good Vibes Mobile DJ','DJ / Entertainment','Mobile DJ and MC services for outdoor gatherings and private events.','Marcus Reed','bookings@goodvibesdj.example.com','(904) 555-0104','https://goodvibesdj.example.com','Northeast Florida','{"w9":"on_file","insurance":"on_file"}','DEMO VENDOR. Marketplace test record.',true,'market-demo-dj-good-vibes','{"four_hour_package_cents":85000}','{"booth_size":"12x12","power_required":true,"water_required":false}',7,4.8,true,'Entertainment','DJs','service','booking_ahead','documents_verified','From $850',100,array['Camping','Weddings','Community Events'],'Usually replies within 2 hours',true),
('Soul Stage Collective','Live Music','Live band and acoustic ensemble booking for community events.','Andre Cole','booking@soulstage.example.com','(904) 555-0118','https://soulstage.example.com','Florida','{"w9":"on_file","insurance":"on_file"}','DEMO VENDOR. Marketplace test record.',true,'market-demo-live-music-soul-stage','{"set_from_cents":120000}','{"booth_size":"16x20","power_required":true,"water_required":false}',4,4.7,true,'Entertainment','Live Music','service','limited','go_melanated_verified','From $1,200',220,array['Festivals','Weddings','Retreats'],'Usually replies same day',false),
('Snap & Spin Booths','Photo Booths','Open-air photo booths, backdrops and digital sharing stations.','Tasha Green','events@snapspin.example.com','(904) 555-0119','https://snapspin.example.com','Jacksonville and Orlando','{"insurance":"on_file"}','DEMO VENDOR. Marketplace test record.',true,'market-demo-photo-booth-snap-spin','{"package_from_cents":65000}','{"booth_size":"10x10","power_required":true,"water_required":false}',5,4.6,true,'Entertainment','Photo Booths','service','available','profile_complete','From $650',150,array['Festivals','Weddings','Community Events'],'Usually replies within 4 hours',false),
('Trail Lens Photo Co.','Photographer','Outdoor event photography, candid coverage and branded galleries.','Imani Lewis','hello@traillens.example.com','(904) 555-0105','https://traillens.example.com','Florida travel available','{"w9":"on_file","insurance":"on_file"}','DEMO VENDOR. Marketplace test record.',true,'market-demo-photo-trail-lens','{"two_hour_cents":45000}','{"booth_size":"none","power_required":false,"water_required":false}',8,4.9,true,'Event Services','Photography','service','available','documents_verified','From $450',350,array['Camping','Festivals','Retreats'],'Usually replies within 2 hours',true),
('Camp Ready Rentals','Rentals','Tables, chairs, tents, coolers, lighting and outdoor event equipment.','Chris Bennett','rentals@campready.example.com','(904) 555-0106','https://campready.example.com','Jacksonville metro','{"w9":"on_file","insurance":"on_file"}','DEMO VENDOR. Marketplace test record.',true,'market-demo-rentals-camp-ready','{"tent_10x20_cents":17500}','{"booth_size":"delivery","power_required":false,"water_required":false}',9,4.6,true,'Event Services','Rentals','service','available','documents_verified','Tents from $175',80,array['Camping','Festivals','Community Events'],'Usually replies same day',true),
('Wild Fern Event Design','Decor','Outdoor event styling, signage, themed decor and installation.','Taylor Grant','design@wildfern.example.com','(904) 555-0107','https://wildfern.example.com','North and Central Florida','{"w9":"on_file","insurance":"on_file"}','DEMO VENDOR. Marketplace test record.',true,'market-demo-decor-wild-fern','{"design_package_from_cents":95000}','{"booth_size":"installation","power_required":true,"water_required":false}',5,4.7,true,'Event Services','Decor','service','booking_ahead','go_melanated_verified','From $950',180,array['Camping','Weddings','Holiday Events'],'Usually replies within 1 day',false),
('Sentinel Event Services','Security','Event staffing for access control, overnight watch and entry support.','Devon Price','ops@sentinelevents.example.com','(904) 555-0108','https://sentinelevents.example.com','Northeast and Central Florida','{"w9":"on_file","insurance":"on_file","license":"on_file"}','DEMO VENDOR. Never treat this record as a real contracted safety resource.',true,'market-demo-security-sentinel','{"hourly_per_staff_cents":4800}','{"booth_size":"none","power_required":false,"water_required":false}',3,4.5,true,'Event Services','Security','service','contact','documents_verified','$48/hr per staff',180,array['Festivals','Camping','Private Events'],'Usually replies within 4 hours',false),
('Sunline Shuttle Co.','Transportation','Passenger shuttle service for parking loops and hotel transfers.','Renee Walker','events@sunlineshuttle.example.com','(904) 555-0109','https://sunlineshuttle.example.com','North Florida','{"w9":"on_file","insurance":"on_file","operating_license":"on_file"}','DEMO VENDOR. Marketplace test record.',true,'market-demo-transport-sunline','{"four_hour_shuttle_cents":125000}','{"booth_size":"vehicle","power_required":false,"water_required":false}',4,4.6,true,'Event Services','Transportation','service','limited','documents_verified','From $1,250',200,array['Festivals','Retreats','Weddings'],'Usually replies same day',false),
('Adventure Spark Experiences','Activities','Field games, guided challenges and family-friendly outdoor programming.','Kai Morgan','hello@adventurespark.example.com','(904) 555-0110','https://adventurespark.example.com','Florida','{"w9":"on_file","insurance":"on_file"}','DEMO VENDOR. Marketplace test record.',true,'market-demo-activities-adventure-spark','{"activity_block_from_cents":70000}','{"booth_size":"20x20","power_required":false,"water_required":false}',6,4.8,true,'Wellness & Activities','Guided Outdoor Activities','service','available','go_melanated_verified','From $700',300,array['Camping','Family Events','Retreats'],'Usually replies within 3 hours',true),
('Stillwater Yoga Co.','Yoga','Group yoga, stretch sessions and sunrise wellness programming.','Brianna Shaw','book@stillwateryoga.example.com','(904) 555-0120','https://stillwateryoga.example.com','Jacksonville and Central Florida','{"insurance":"on_file"}','DEMO VENDOR. Marketplace test record.',true,'market-demo-yoga-stillwater','{"session_from_cents":30000}','{"booth_size":"open_space","power_required":false,"water_required":false}',3,4.9,true,'Wellness & Activities','Yoga','service','available','profile_complete','From $300/session',160,array['Camping','Retreats','Wellness Events'],'Usually replies within 4 hours',false),
('Move Free Fitness','Fitness','Outdoor group fitness, bootcamps and beginner-friendly movement sessions.','Jalen Price','events@movefree.example.com','(904) 555-0121','https://movefree.example.com','North Florida','{"insurance":"on_file"}','DEMO VENDOR. Marketplace test record.',true,'market-demo-fitness-move-free','{"class_from_cents":35000}','{"booth_size":"open_space","power_required":false,"water_required":false}',2,4.6,true,'Wellness & Activities','Fitness','service','booking_ahead','profile_complete','From $350/class',120,array['Camping','Corporate Events','Community Events'],'Usually replies same day',false),
('Cypress Grove Retreat','Venue','Private outdoor retreat venue with cabins, field space and group amenities.','Morgan Lee','events@cypressgrove.example.com','(352) 555-0122','https://cypressgrove.example.com','Central Florida','{"insurance":"on_file","venue_packet":"on_file"}','DEMO VENUE. Marketplace test record.',true,'market-demo-venue-cypress-grove','{"day_from_cents":220000}','{"booth_size":"venue","power_required":true,"water_required":true}',10,4.8,true,'Venues & Lodging','Retreat Centers','venue','limited','documents_verified','From $2,200/day',null,array['Camping','Retreats','Family Events'],'Usually replies within 1 day',true),
('Pine Lake Campground','Venue','Group camping, pavilion rentals and event-friendly campsites.','Robin Carter','groups@pinelakecamp.example.com','(352) 555-0123','https://pinelakecamp.example.com','North Central Florida','{"venue_packet":"on_file"}','DEMO VENUE. Marketplace test record.',true,'market-demo-campground-pine-lake','{"site_from_cents":4000}','{"booth_size":"venue","power_required":true,"water_required":true}',12,4.7,true,'Venues & Lodging','Campgrounds','venue','booking_ahead','profile_complete','Sites from $40/night',null,array['Camping','Family Events','Retreats'],'Usually replies same day',true),
('Canvas & Pine Glamping','Glamping','Mobile glamping setups, furnished bell tents and group packages.','Noelle Grant','hello@canvaspine.example.com','(407) 555-0124','https://canvaspine.example.com','Florida','{"insurance":"on_file"}','DEMO VENDOR. Marketplace test record.',true,'market-demo-glamping-canvas-pine','{"tent_from_cents":27500}','{"booth_size":"site_setup","power_required":false,"water_required":false}',6,4.8,true,'Venues & Lodging','Glamping Providers','service','booking_ahead','go_melanated_verified','From $275/tent',300,array['Camping','Retreats','Weddings'],'Usually replies within 4 hours',false),
('Rooted Goods Market','Merchandise','Outdoor lifestyle goods, accessories and small-batch gifts.','Amina Wells','market@rootedgoods.example.com','(904) 555-0111','https://rootedgoods.example.com','Jacksonville and regional travel','{"w9":"on_file","insurance":"pending"}','DEMO VENDOR. Marketplace test record with pending insurance.',true,'market-demo-merch-rooted-goods','{"vendor_fee_example_cents":15000}','{"booth_size":"10x10","power_required":false,"water_required":false}',2,4.4,true,'Retail & Sales','Outdoor Gear','product','available','profile_complete','Items from $15',120,array['Camping','Markets','Festivals'],'Usually replies same day',false),
('Pine & Palm Venue Services','Venue Services','Setup coordination, trash stations, restroom servicing and event-day logistics.','Morgan Ellis','events@pineandpalm.example.com','(904) 555-0112','https://pineandpalm.example.com','North Florida','{"w9":"on_file","insurance":"on_file"}','DEMO VENDOR. Marketplace test record.',true,'market-demo-venue-services-pine-palm','{"event_support_from_cents":60000}','{"booth_size":"service","power_required":false,"water_required":false}',5,4.7,true,'Event Services','Staffing & Cleanup','service','available','documents_verified','From $600/event',140,array['Festivals','Camping','Community Events'],'Usually replies within 3 hours',false)
on conflict (demo_key) do update set
  business_name = excluded.business_name,
  category = excluded.category,
  description = excluded.description,
  contact_name = excluded.contact_name,
  email = excluded.email,
  phone = excluded.phone,
  website = excluded.website,
  service_area = excluded.service_area,
  documents = excluded.documents,
  internal_notes = excluded.internal_notes,
  is_demo = true,
  sample_pricing = excluded.sample_pricing,
  typical_setup = excluded.typical_setup,
  demo_event_count = excluded.demo_event_count,
  rating = excluded.rating,
  marketplace_visible = true,
  marketplace_category = excluded.marketplace_category,
  marketplace_subcategory = excluded.marketplace_subcategory,
  vendor_kind = excluded.vendor_kind,
  availability_status = excluded.availability_status,
  verification_status = excluded.verification_status,
  starting_price_text = excluded.starting_price_text,
  travel_radius_miles = excluded.travel_radius_miles,
  event_types = excluded.event_types,
  response_time_text = excluded.response_time_text,
  featured = excluded.featured,
  updated_at = now();