create table if not exists public.host_event_connections (
  id uuid primary key default gen_random_uuid(),
  campaign_id uuid not null references public.host_campaigns(id) on delete cascade,
  provider text not null check (provider in ('eventbrite','facebook','instagram','email','go_melanated','sms','other')),
  external_account_id text,
  external_event_id text,
  display_name text,
  status text not null default 'connected' check (status in ('connected','attention','disconnected')),
  capabilities jsonb not null default '{}'::jsonb,
  last_synced_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (campaign_id, provider, external_event_id)
);

create table if not exists public.host_event_promotions (
  id uuid primary key default gen_random_uuid(),
  campaign_id uuid not null references public.host_campaigns(id) on delete cascade,
  connection_id uuid references public.host_event_connections(id) on delete set null,
  promotion_key text not null,
  channel text not null,
  content_type text,
  title text,
  destination_url text,
  tracking_code text,
  scheduled_for timestamptz,
  published_at timestamptz,
  status text not null default 'draft' check (status in ('draft','scheduled','published','paused','complete','cancelled')),
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (campaign_id, promotion_key)
);

create table if not exists public.host_event_analytics_events (
  id bigint generated by default as identity primary key,
  campaign_id uuid not null references public.host_campaigns(id) on delete cascade,
  promotion_id uuid references public.host_event_promotions(id) on delete set null,
  connection_id uuid references public.host_event_connections(id) on delete set null,
  event_name text not null check (event_name in ('promotion_impression','promotion_reach','promotion_view','promotion_click','event_page_view','checkout_started','ticket_ordered','ticket_refunded','attendee_checked_in','message_delivered','message_opened','message_clicked')),
  source text not null,
  external_id text,
  quantity integer not null default 1,
  value_cents integer not null default 0,
  occurred_at timestamptz not null default now(),
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create index if not exists host_event_analytics_campaign_time_idx on public.host_event_analytics_events(campaign_id, occurred_at desc);
create index if not exists host_event_analytics_source_idx on public.host_event_analytics_events(campaign_id, source, event_name);

create table if not exists public.host_event_ticket_sources (
  id uuid primary key default gen_random_uuid(),
  campaign_id uuid not null references public.host_campaigns(id) on delete cascade,
  connection_id uuid references public.host_event_connections(id) on delete set null,
  source text not null,
  external_ticket_class_id text,
  label text not null,
  capacity integer,
  sold integer not null default 0,
  gross_revenue_cents integer not null default 0,
  refunded_cents integer not null default 0,
  last_synced_at timestamptz,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.host_event_connections enable row level security;
alter table public.host_event_promotions enable row level security;
alter table public.host_event_analytics_events enable row level security;
alter table public.host_event_ticket_sources enable row level security;

create policy "Campaign staff can read event connections" on public.host_event_connections for select to authenticated using ((select app_private.can_access_host_campaign(campaign_id)));
create policy "Campaign managers manage event connections" on public.host_event_connections for all to authenticated using ((select app_private.can_manage_host_campaign(campaign_id))) with check ((select app_private.can_manage_host_campaign(campaign_id)));

create policy "Campaign staff can read promotions" on public.host_event_promotions for select to authenticated using ((select app_private.can_access_host_campaign(campaign_id)));
create policy "Campaign managers manage promotions" on public.host_event_promotions for all to authenticated using ((select app_private.can_manage_host_campaign(campaign_id))) with check ((select app_private.can_manage_host_campaign(campaign_id)));

create policy "Campaign staff can read event analytics" on public.host_event_analytics_events for select to authenticated using ((select app_private.can_access_host_campaign(campaign_id)));
create policy "Campaign managers insert event analytics" on public.host_event_analytics_events for insert to authenticated with check ((select app_private.can_manage_host_campaign(campaign_id)));

create policy "Campaign staff can read ticket sources" on public.host_event_ticket_sources for select to authenticated using ((select app_private.can_access_host_campaign(campaign_id)));
create policy "Campaign managers manage ticket sources" on public.host_event_ticket_sources for all to authenticated using ((select app_private.can_manage_host_campaign(campaign_id))) with check ((select app_private.can_manage_host_campaign(campaign_id)));
