create table if not exists public.host_ai_preferences (
  profile_id uuid primary key references public.profiles(id) on delete cascade,
  personal_memory_enabled boolean not null default false,
  event_history_learning_enabled boolean not null default false,
  organization_memory_enabled boolean not null default false,
  save_conversations_enabled boolean not null default false,
  product_analytics_enabled boolean not null default false,
  recommendation_history_enabled boolean not null default false,
  updated_at timestamptz not null default now()
);

alter table public.host_ai_preferences enable row level security;
create policy "Users can read own AI preferences" on public.host_ai_preferences for select to authenticated using (profile_id = auth.uid());
create policy "Users can insert own AI preferences" on public.host_ai_preferences for insert to authenticated with check (profile_id = auth.uid());
create policy "Users can update own AI preferences" on public.host_ai_preferences for update to authenticated using (profile_id = auth.uid()) with check (profile_id = auth.uid());

create table if not exists public.host_ai_planner_sessions (
  id uuid primary key default gen_random_uuid(),
  profile_id uuid not null references public.profiles(id) on delete cascade,
  adventure_id uuid references public.adventures(id) on delete set null,
  status text not null default 'planning' check (status in ('planning','created','closed')),
  event_type text,
  readiness integer not null default 0 check (readiness between 0 and 100),
  plan jsonb not null default '{}'::jsonb,
  required_gaps jsonb not null default '[]'::jsonb,
  recommended_components jsonb not null default '[]'::jsonb,
  task_packs jsonb not null default '[]'::jsonb,
  conversation jsonb not null default '[]'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.host_ai_planner_sessions enable row level security;
create policy "Users can read own AI planner sessions" on public.host_ai_planner_sessions for select to authenticated using (profile_id = auth.uid());
create policy "Users can create own AI planner sessions" on public.host_ai_planner_sessions for insert to authenticated with check (profile_id = auth.uid());
create policy "Users can update own AI planner sessions" on public.host_ai_planner_sessions for update to authenticated using (profile_id = auth.uid()) with check (profile_id = auth.uid());
create policy "Users can delete own AI planner sessions" on public.host_ai_planner_sessions for delete to authenticated using (profile_id = auth.uid());

create table if not exists public.host_ai_memories (
  id uuid primary key default gen_random_uuid(),
  profile_id uuid not null references public.profiles(id) on delete cascade,
  memory_type text not null check (memory_type in ('explicit','learned')),
  key text not null,
  value jsonb not null,
  confidence numeric(4,3),
  source_event_id uuid references public.adventures(id) on delete set null,
  active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
create unique index if not exists host_ai_memories_profile_key_idx on public.host_ai_memories(profile_id, key) where active;
alter table public.host_ai_memories enable row level security;
create policy "Users manage own AI memories" on public.host_ai_memories for all to authenticated using (profile_id = auth.uid()) with check (profile_id = auth.uid());

create table if not exists public.host_ai_product_events (
  id bigint generated by default as identity primary key,
  profile_id uuid references public.profiles(id) on delete set null,
  planner_session_id uuid references public.host_ai_planner_sessions(id) on delete set null,
  event_name text not null,
  event_type text,
  intent_type text,
  question_category text,
  recommendation_type text,
  recommendation_accepted boolean,
  readiness_before integer,
  readiness_after integer,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);
alter table public.host_ai_product_events enable row level security;
create policy "Users can create own optional AI analytics" on public.host_ai_product_events for insert to authenticated with check (profile_id = auth.uid());
create policy "Users can read own optional AI analytics" on public.host_ai_product_events for select to authenticated using (profile_id = auth.uid());